### ISSUE TITLE
It can't register account at first when application start with an empty database for AccountManagement sample

### ISSUE THREAD

**Issue by ericwp** [mlidbom/Composable#39]
I found a problem for AccountManagement sample, If I running it with empty database, when application start, it will only create InboxMessages, MessageDispatching, OutboxMessages. If I running register at once it will throw "Invalid object name 'ValueType'." which caused by bus.Execute(AccountApi.Queries.TryGetByEmail(email)) is Some<Account>. By if I login first with any account, it will create store and ValueType tables, then everything works.

**Comment by mlidbom** [comment]
Hi. Thank you for taking the time to file an issue :)

I've tried several times to recreate the problem without success.
Please try it again and ensure that you have:
* The latest code from the develop branch
* A database that is completely empty.
* No application server window running in the background when you empty out the database.

Does it still happen? If it does, could you please post detailed step by step instructions for recreating the problem?

**Comment by ericwp** [comment]
The steps are as following 

1. Create an empty database for AccountManagement
2. Running AccountManagement.Server and AccountManagement.UI.MVC
3. Register account directly
4. I will get following errors
   An unhandled exception occurred while processing the request.
  MessageDispatchingFailedException: Dispatching message failed. Remote exception message: 
  ##################################################
  System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ValueType'.
  ...

**Comment by mlidbom** [comment]
Strange.

That sounds like the same procedure that I use. I just tried it two more times and it works fine for me.
Could you please provide the complete stack trace?

**Comment by ericwp** [comment]
MessageDispatchingFailedException: Dispatching message failed. Remote exception message: 
 ##################################################
 System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ValueType'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
 at System.Data.SqlClient.SqlDataReader.get_MetaData()
 at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
 at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
 at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
 at System.Data.SqlClient.SqlCommand.ExecuteReader()
 at Composable.System.Data.SqlClient.SqlCommandExtensions.ExecuteReader(SqlCommand this, String commandText)
 at Composable.System.Data.SqlClient.SqlCommandExtensions.ExecuteReader(SqlCommand this, String commandText, Action`1 forEach)
 at Composable.System.Data.SqlClient.SqlConnectionProviderExtensions.<>c__DisplayClass2_0.<ExecuteReader>b__0(SqlCommand command)
 at Composable.System.Data.SqlClient.SqlConnectionExtensions.UseCommand(SqlConnection this, Action`1 action)
 at Composable.System.Data.SqlClient.SqlConnectionProviderExtensions.<>c__DisplayClass5_0.<UseCommand>b__0(SqlConnection connection)
 at Composable.System.Data.SqlClient.SqlConnectionProviderExtensions.UseConnection(ISqlConnectionProvider this, Action`1 action)
 at Composable.System.Data.SqlClient.SqlConnectionProviderExtensions.UseCommand(ISqlConnectionProvider this, Action`1 action)
 at Composable.System.Data.SqlClient.SqlConnectionProviderExtensions.ExecuteReader(ISqlConnectionProvider this, String commandText, Action`1 forEach)
 at Composable.Persistence.DocumentDb.SqlServer.SqlServerDocumentDb.RefreshKnownTypes()
 at Composable.Persistence.DocumentDb.SqlServer.SqlServerDocumentDb.IsKnownType(Type type)
 at Composable.Persistence.DocumentDb.SqlServer.SqlServerDocumentDb.Composable.Persistence.DocumentDb.IDocumentDb.TryGet[TValue](Object key, TValue& value, Dictionary`2 persistentValues)
 at Composable.Persistence.DocumentDb.DocumentDbSession.TryGetInternal[TValue](Object key, Type documentType, TValue& value)
 at Composable.Persistence.DocumentDb.DocumentDbSession.TryGet[TValue](Object key, TValue& document)
 at Composable.Persistence.DocumentDb.DocumentDbApi.Query.TryGetDocument`1.<>c.<RegisterHandler>b__5_0(TryGetDocument`1 query, IDocumentDbReader updater)
 at Composable.Messaging.Buses.MessageHandlerRegistrarWithDependencyInjectionSupportExtensions.<>c__DisplayClass31_0`3.<ForQuery>b__0(TQuery query)
 at Composable.Messaging.Buses.Implementation.MessageHandlerRegistry.QueryHandlerRegistration`2.<>c__DisplayClass0_0.<.ctor>b__0(Object command)
 at Composable.Messaging.Buses.Implementation.MessageHandlerRegistry.<>c__DisplayClass18_0`1.<Composable.Messaging.Buses.Implementation.IMessageHandlerRegistry.GetQueryHandler>b__0(IQuery`1 actualQuery)
 at Composable.Messaging.Buses.ApiNavigatorSession.Composable.Messaging.Buses.ILocalApiNavigatorSession.Execute[TResult](IQuery`1 query)
 at AccountManagement.Domain.EmailToAccountMapper.<>c.<TryGetAccountByEmail>b__3_0(TryGetByEmailQuery query, ILocalApiNavigatorSession bus)
 at Composable.Messaging.Buses.MessageHandlerRegistrarWithDependencyInjectionSupportExtensions.<>c__DisplayClass31_0`3.<ForQuery>b__0(TQuery query)
 at Composable.Messaging.Buses.Implementation.MessageHandlerRegistry.QueryHandlerRegistration`2.<>c__DisplayClass0_0.<.ctor>b__0(Object command)
 at Composable.Messaging.Buses.Implementation.MessageHandlerRegistry.<>c__DisplayClass18_0`1.<Composable.Messaging.Buses.Implementation.IMessageHandlerRegistry.GetQueryHandler>b__0(IQuery`1 actualQuery)
 at Composable.Messaging.Buses.ApiNavigatorSession.Composable.Messaging.Buses.ILocalApiNavigatorSession.Execute[TResult](IQuery`1 query)
 at AccountManagement.Domain.Account.Register(Guid accountId, Email email, Password password, ILocalApiNavigatorSession bus)
 at AccountManagement.UI.AccountUIAdapter.<>c.<Register>b__3_0(Register command, ILocalApiNavigatorSession bus)
 at Composable.Messaging.Buses.MessageHandlerRegistrarWithDependencyInjectionSupportExtensions.<>c__DisplayClass11_0`3.<ForCommandWithResult>b__0(TCommand command)
 at Composable.Messaging.Buses.Implementation.MessageHandlerRegistry.CommandHandlerWithResultRegistration`2.<>c__DisplayClass0_0.<.ctor>b__0(Object command)
 at Composable.Messaging.Buses.Implementation.Inbox.HandlerExecutionEngine.Coordinator.HandlerExecutionTask.<CreateMessageTask>b__15_1(Object message)
 at Composable.Messaging.Buses.Implementation.Inbox.HandlerExecutionEngine.Coordinator.HandlerExecutionTask.<>c__DisplayClass13_0.<Execute>b__1()
 at Composable.System.Transactions.TransactionScopeCe.Execute[TResult](Func`1 action, TransactionScopeOption option, IsolationLevel isolationLevel)
 at Composable.DependencyInjection.ServiceLocatorTransactionRunner.ExecuteTransactionInIsolatedScope[TResult](IServiceLocator me, Func`1 function)
 at Composable.Messaging.Buses.Implementation.Inbox.HandlerExecutionEngine.Coordinator.HandlerExecutionTask.<>c__DisplayClass13_0.<Execute>b__0()
 ClientConnectionId:5c0e9eaa-3024-4521-90e1-fefe536065f3
 Error Number:208,State:1,Class:16 
 #################################################
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.Implementation.ClientConnection+<>c__DisplayClass8_0+<<DispatchAsync>b__0>d.MoveNext() in ClientConnection.cs
+
            return await taskCompletionSource.Task;
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.Implementation.ClientConnection+<DispatchAsync>d__8.MoveNext() in ClientConnection.cs
+
        public async Task<TCommandResult> DispatchAsync<TCommandResult>(BusApi.Remotable.AtMostOnce.ICommand<TCommandResult> command) => (TCommandResult)await _state.WithExclusiveAccess(async state =>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.Implementation.InterprocessTransport+<>c__DisplayClass10_0+<<DispatchAsync>b__0>d.MoveNext() in InterprocessTransport.cs
+
            return await connection.DispatchAsync(atMostOnceCommand);
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.Implementation.InterprocessTransport+<DispatchAsync>d__10.MoveNext() in InterprocessTransport.cs
+
        public async Task<TCommandResult> DispatchAsync<TCommandResult>(BusApi.Remotable.AtMostOnce.ICommand<TCommandResult> atMostOnceCommand) => await _state.WithExclusiveAccess(async state =>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
Composable.Messaging.Buses.RemoteApiBrowserSession+<Composable-Messaging-Buses-IRemoteApiNavigatorSession-PostAsync>d__5.MoveNext() in RemoteApiBrowser.cs
+
            return await _transport.DispatchAsync(command).NoMarshalling();
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.NavigationSpecification+StartCommand+<NavigateOnAsync>d__2.MoveNext() in NavigationSpecification.cs
+
            public override async Task<TResult> NavigateOnAsync(IRemoteApiNavigatorSession busSession) => await busSession.PostAsync(_start);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Composable.System.Threading.TaskExtensions.ResultUnwrappingException<TResult>(Task<TResult> task) in TaskExtensions.cs
+
                    ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
Composable.Messaging.NavigationSpecification.NavigateOn(IRemoteApiNavigatorSession busSession) in NavigationSpecification.cs
+
        public TResult NavigateOn(IRemoteApiNavigatorSession busSession) => NavigateOnAsync(busSession).ResultUnwrappingException();
Composable.Messaging.NavigationSpecificationMessageExtensions.PostOn<TResult>(ICommand<TResult> command, IRemoteApiNavigatorSession bus) in NavigationSpecificationMessageExtensions.cs
+
        public static TResult PostOn<TResult>(this BusApi.Remotable.AtMostOnce.ICommand<TResult> command, IRemoteApiNavigatorSession bus) => NavigationSpecification.Post(command).NavigateOn(bus);
AccountManagement.UI.MVC.Views.Register.RegisterController.Register(Register registrationCommand) in RegisterController.cs
+
            var result = registrationCommand.PostOn(_bus);
lambda_method(Closure , object , Object[] )
Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, Object[] parameters)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AccountManagement.UI.MVC.Startup+<>c__DisplayClass7_0+<<Configure>b__2>d.MoveNext() in Startup.cs
+
            app.Use(async (context, next) => await _clientEndpoint.ExecuteRequestAsync(async () => await next.Invoke()));
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.EndpointRequestExecutor+<>c__DisplayClass7_0+<<ExecuteRequestAsync>b__0>d.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Composable.Messaging.Buses.EndpointRequestExecutor+<ExecuteRequestAsync>d__7.MoveNext() in EndpointRequestExecutor.cs
+
        public static async Task ExecuteRequestAsync(this IEndpoint endpoint, Func<Task> request) =>await endpoint.ServiceLocator.ExecuteInIsolatedScope(async () => await request());
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AccountManagement.UI.MVC.Startup+<<Configure>b__7_0>d.MoveNext() in Startup.cs
+
            app.Use(async (context, next) => await _clientEndpoint.ExecuteRequestAsync(async () => await next.Invoke()));
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by mlidbom** [comment]
Wait a minute: 

> If I running register at once it will throw "Invalid object name 'ValueType'." which caused by bus.Execute(AccountApi.Queries.TryGetByEmail(email)) is Some. By if I login first with any account, it will create store and ValueType tables, then everything works.

If you start with an empty database there are no Accounts so how can you log in with one?
And the code that creates the tables is exactly the same regardless of whether you are registering or trying to log in. I cannot understand how it is even theoretically possible for it to work differently between the two scenarios. And I'm completely unable to reproduce this problem no matter how I try. I've spent hours now.

Could you please confirm that you have repeated these instructions step by step yourself?
* Delete the AccountManagement database.
* Make sure that NO instances of any AccountManagement services are running.
* Create a new AccountManagement database
* Start The UI and the Server and try to register an account.

If you have I'm completely stumped. I cannot understand how this could happen.

**Comment by ericwp** [comment]
I can recreate always. I think I know the problem, when the first time running, it will running EnsureInitialized(Composable.Persistence.DocumentDb.SqlServer.SqlServerDocumentDb) and create ValueType and Store table, but it don't in transaction. 
For register when applicatin start, it will EnsureInitialized at first, but never commit, after that, it will run SqlServerEventStoreSchemaManager.SetupSchemaIfDatabaseUnInitialized(), it crash from here, I guess it locked some master table(sys.tables).
For login(you should restart application again), because the account not exist, it needn't save event. When return login failed,  ValueType and Store were created. I guess it will commit when connection closed. That is why I said the login works
That may explain when I running register after application start it will crash, but not for login with not exist account.

I did changes for Composable.Persistence.DocumentDb.SqlServer.SqlServerDocumentDb.EnsureInitialized as following, it works well any 
internal void EnsureInitialized() => TransactionScopeCe.SuppressAmbientAndExecuteInNewTransaction(() =>{
.....
});

Is that correct?

**Comment by mlidbom** [comment]
Ah, that could explain it I guess. Sounds like a race condition that does not happen on my machine due to different performance characteristics. Looking at that code it was indeed vulnerable to race conditions, and the change that you suggested should indeed fix that as far as I can tell.

I've pushed a commit that makes the change you proposed. Hopefully I understood you correctly.
Could you test it now and se if it fixes the issue for you?

**Comment by mlidbom** [comment]
I hope that you will keep reporting issues when you find a problem.
The next time

**Comment by mlidbom** [comment]
I really appreciate that you took the time to diagnose this and provide a fix! The next time you have a suggested code fix it would be even better if you could create a pull request :)

**Comment by ericwp** [comment]
Sure, I will do that :)
